package codemeans.shopify4j.admin.rest.model.enums;

import codemeans.shopify4j.admin.rest.internal.ShopifyEnum;

/**
 * @author: yuanwq
 * @date: 2021-01-18
 */
public enum TaxExemption implements ShopifyEnum<TaxExemption> {

  EXEMPT_ALL,
  CA_STATUS_CARD_EXEMPTION,
  CA_DIPLOMAT_EXEMPTION,
  CA_BC_RESELLER_EXEMPTION,
  CA_MB_RESELLER_EXEMPTION,
  CA_SK_RESELLER_EXEMPTION,
  CA_BC_COMMERCIAL_FISHERY_EXEMPTION,
  CA_MB_COMMERCIAL_FISHERY_EXEMPTION,
  CA_NS_COMMERCIAL_FISHERY_EXEMPTION,
  CA_PE_COMMERCIAL_FISHERY_EXEMPTION,
  CA_SK_COMMERCIAL_FISHERY_EXEMPTION,
  CA_BC_PRODUCTION_AND_MACHINERY_EXEMPTION,
  CA_SK_PRODUCTION_AND_MACHINERY_EXEMPTION,
  CA_BC_SUB_CONTRACTOR_EXEMPTION,
  CA_SK_SUB_CONTRACTOR_EXEMPTION,
  CA_BC_CONTRACTOR_EXEMPTION,
  CA_SK_CONTRACTOR_EXEMPTION,
  CA_ON_PURCHASE_EXEMPTION,
  CA_MB_FARMER_EXEMPTION,
  CA_NS_FARMER_EXEMPTION,
  CA_SK_FARMER_EXEMPTION,
  ;

  @Override
  public String shopifyValue() {
    return name().toUpperCase();
  }
}
